{
 "title": "Копилка",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Common services",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "node_systemd_unit_state{name=\"smbd.service\",state=\"active\",type=\"notify\"} ",
     "legendFormat": "Samba"
    },
    {
     "expr": "node_systemd_unit_state{name=\"apache2.service\",state=\"active\",type=\"forking\"}",
     "legendFormat": "Apache2"
    },
    {
     "expr": "node_systemd_unit_state{name=\"transmission-daemon.service\",state=\"active\",type=\"notify\"} ",
     "legendFormat": "Transmiss"
    },
    {
     "expr": "node_systemd_unit_state{name=\"serviio.service\",state=\"active\",type=\"idle\"}",
     "legendFormat": "Serviio"
    },
    {
     "expr": "node_systemd_unit_state{name=\"mysql.service\",state=\"active\",type=\"notify\"}",
     "legendFormat": "Mysqld"
    }
   ]
  },
  {
   "title": "CPU  idle",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m])) * 100"
    }
   ]
  },
  {
   "title": "RAID stripe(bkp drive)  ok",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "(node_md_disks_active{device=\"md126\"})/ (node_md_disks{device=\"md126\"})",
     "legendFormat": "RAID  целостный"
    }
   ]
  },
  {
   "title": "Free on root / ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{device=\"/dev/sde2\",fstype=\"ext4\",mountpoint=\"/\"}",
     "legendFormat": "SDE Гб"
    }
   ]
  },
  {
   "title": "Traffic throughput ",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=\"enp5s0\"}[30s])",
     "legendFormat": "Receive"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=\"enp5s0\"}[30s])",
     "legendFormat": "transmit"
    }
   ]
  },
  {
   "title": "Reboot flg",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(process_start_time_seconds[5m])",
     "legendFormat": "reboot"
    }
   ]
  },
  {
   "title": "CPULA 1/5/15",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 2, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "1"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "5"
    },
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{job=\"node\",mode=\"idle\"}[15m])) * 100)",
     "legendFormat": "15"
    }
   ]
  },
  {
   "title": "MEM Free",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "free_MEM" }
   ]
  }
 ]
}